=== erpuno/hl7/schema/BodyStructure.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "id": "http://hl7.erp.uno/schema/BodyStructure.schema.json",
  "$ref": "#/definitions/BodyStructure",
  "description": "see http://hl7.org/fhir/json.html#schema for information about the FHIR Json Schemas",
  "definitions": {
    "markdown": {
      "pattern": "^^[\\s\\S]+$$",
      "type": "string",
      "description": "A string that may contain Github Flavored Markdown syntax for optional processing by a mark down presentation engine"
    },
    "code": {
      "pattern": "^[^\\s]+( [^\\s]+)*$",
      "type": "string",
      "description": "A string which has at least one character and no leading or trailing whitespace and where there is no whitespace other than single spaces in the contents"
    },
    "uri": {
      "pattern": "^\\S*$",
      "type": "string",
      "description": "String of characters used to identify a name or a resource"
    },
    "BodyStructure": {
      "description": "Record details about an anatomical structure.  This resource may be used when a coded concept does not provide the necessary detail needed for the use case.",
      "properties": {
        "resourceType": {
          "description": "This is a BodyStructure resource",
          "const": "BodyStructure"
        },
        "id": {
          "description": "The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.",
          "type": "string"
        },
        "meta": {
          "description": "The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.",
          "$ref": "Meta.schema.json#/definitions/Meta"
        },
        "implicitRules": {
          "description": "A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc.",
          "$ref": "#/definitions/uri"
        },
        "_implicitRules": {
          "description": "Extensions for implicitRules",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "language": {
          "description": "The base language in which the resource is written.",
          "$ref": "#/definitions/code"
        },
        "_language": {
          "description": "Extensions for language",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "text": {
          "description": "A human-readable narrative that contains a summary of the resource and can be used to represent the content of the resource to a human. The narrative need not encode all the structured data, but is required to contain sufficient detail to make it \"clinically safe\" for a human to just read the narrative. Resource definitions may define what content should be represented in the narrative to ensure clinical safety.",
          "$ref": "Narrative.schema.json#/definitions/Narrative"
        },
        "contained": {
          "description": "These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, nor can they have their own independent transaction scope. This is allowed to be a Parameters resource if and only if it is referenced by a resource that provides context/meaning.",
          "items": {
            "$ref": "ResourceList.schema.json#/definitions/ResourceList"
          },
          "type": "array"
        },
        "extension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "modifierExtension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding of the containing element\u0027s descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer is allowed to define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.\n\nModifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "identifier": {
          "description": "Identifier for this instance of the anatomical structure.",
          "items": {
            "$ref": "Identifier.schema.json#/definitions/Identifier"
          },
          "type": "array"
        },
        "active": {
          "description": "Whether this body site is in active use.",
          "type": "boolean"
        },
        "_active": {
          "description": "Extensions for active",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "morphology": {
          "description": "The kind of structure being represented by the body structure at `BodyStructure.location`.  This can define both normal and abnormal morphologies.",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "includedStructure": {
          "description": "The anatomical location(s) or region(s) of the specimen, lesion, or body structure.",
          "items": {
            "$ref": "#/definitions/BodyStructure_IncludedStructure"
          },
          "type": "array"
        },
        "excludedStructure": {
          "description": "The anatomical location(s) or region(s) not occupied or represented by the specimen, lesion, or body structure.",
          "items": {
            "$ref": "#/definitions/BodyStructure_IncludedStructure"
          },
          "type": "array"
        },
        "description": {
          "description": "A summary, characterization or explanation of the body structure.",
          "$ref": "#/definitions/markdown"
        },
        "_description": {
          "description": "Extensions for description",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "image": {
          "description": "Image or images used to identify a location.",
          "items": {
            "$ref": "Attachment.schema.json#/definitions/Attachment"
          },
          "type": "array"
        },
        "patient": {
          "description": "The person to which the body site belongs.",
          "$ref": "Reference.schema.json#/definitions/Reference"
        }
      },
      "type": "object",
      "additionalProperties": false,
      "required": [
        "includedStructure",
        "patient",
        "resourceType"
      ]
    },
    "BodyStructure_IncludedStructure": {
      "description": "Record details about an anatomical structure.  This resource may be used when a coded concept does not provide the necessary detail needed for the use case.",
      "properties": {
        "id": {
          "description": "Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.",
          "type": "string"
        },
        "extension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "modifierExtension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element\u0027s descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.\n\nModifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "structure": {
          "description": "Code that represents the included structure.",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "laterality": {
          "description": "Code that represents the included structure laterality.",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "bodyLandmarkOrientation": {
          "description": "Body locations in relation to a specific body landmark (tatoo, scar, other body structure).",
          "items": {
            "$ref": "#/definitions/BodyStructure_BodyLandmarkOrientation"
          },
          "type": "array"
        },
        "spatialReference": {
          "description": "XY or XYZ-coordinate orientation for structure.",
          "items": {
            "$ref": "Reference.schema.json#/definitions/Reference"
          },
          "type": "array"
        },
        "qualifier": {
          "description": "Code that represents the included structure qualifier.",
          "items": {
            "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
          },
          "type": "array"
        }
      },
      "type": "object",
      "additionalProperties": false,
      "required": [
        "structure"
      ]
    },
    "BodyStructure_BodyLandmarkOrientation": {
      "description": "Record details about an anatomical structure.  This resource may be used when a coded concept does not provide the necessary detail needed for the use case.",
      "properties": {
        "id": {
          "description": "Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.",
          "type": "string"
        },
        "extension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "modifierExtension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element\u0027s descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.\n\nModifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "landmarkDescription": {
          "description": "A description of a landmark on the body used as a reference to locate something else.",
          "items": {
            "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
          },
          "type": "array"
        },
        "clockFacePosition": {
          "description": "An description of the direction away from a landmark something is located based on a radial clock dial.",
          "items": {
            "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
          },
          "type": "array"
        },
        "distanceFromLandmark": {
          "description": "The distance in centimeters a certain observation is made from a body landmark.",
          "items": {
            "$ref": "#/definitions/BodyStructure_DistanceFromLandmark"
          },
          "type": "array"
        },
        "surfaceOrientation": {
          "description": "The surface area a body location is in relation to a landmark.",
          "items": {
            "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
          },
          "type": "array"
        }
      },
      "type": "object",
      "additionalProperties": false
    },
    "BodyStructure_DistanceFromLandmark": {
      "description": "Record details about an anatomical structure.  This resource may be used when a coded concept does not provide the necessary detail needed for the use case.",
      "properties": {
        "id": {
          "description": "Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.",
          "type": "string"
        },
        "extension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "modifierExtension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element\u0027s descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.\n\nModifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "device": {
          "description": "An instrument, tool, analyzer, etc. used in the measurement.",
          "items": {
            "$ref": "CodeableReference.schema.json#/definitions/CodeableReference"
          },
          "type": "array"
        },
        "value": {
          "description": "The measured distance (e.g., in cm) from a body landmark.",
          "items": {
            "$ref": "Quantity.schema.json#/definitions/Quantity"
          },
          "type": "array"
        }
      },
      "type": "object",
      "additionalProperties": false
    }
  }
}

=== erpuno/hl7/samples/json/BodyStructure/BodyStructure.json
{
  "resourceType" : "BodyStructure",
  "id" : "fetus",
  "text" : {
    "status" : "generated",
    "div" : "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Generated Narrative: BodyStructure</b><a name=\"fetus\"> </a></p><div style=\"display: inline-block; background-color: #d9e0e7; padding: 6px; margin: 4px; border: 1px solid #8da1b4; border-radius: 5px; line-height: 60%\"><p style=\"margin-bottom: 0px\">Resource BodyStructure &quot;fetus&quot; </p></div><p><b>identifier</b>: id:\u00a012345</p><h3>IncludedStructures</h3><table class=\"grid\"><tr><td>-</td><td><b>Structure</b></td></tr><tr><td>*</td><td>Fetus <span style=\"background: LightGoldenRodYellow; margin: 4px; border: 1px solid khaki\"> (<a href=\"https://browser.ihtsdotools.org/\">SNOMED CT</a>#83418008 &quot;Entire fetus (body structure)&quot;)</span></td></tr></table><p><b>description</b>: EDD 1/1/2017 confirmation by LMP</p><p><b>patient</b>: <a href=\"patient-example.html\">Patient/example</a> &quot;Peter CHALMERS&quot;</p></div>"
  },
  "identifier" : [{
    "system" : "http://goodhealth.org/bodystructure/identifiers",
    "value" : "12345"
  }],
  "includedStructure" : [{
    "structure" : {
      "coding" : [{
        "system" : "http://snomed.info/sct",
        "code" : "83418008",
        "display" : "Entire fetus (body structure)"
      }],
      "text" : "Fetus"
    }
  }],
  "description" : "EDD 1/1/2017 confirmation by LMP",
  "patient" : {
    "reference" : "Patient/example"
  }
}
