=== erpuno/hl7/schema/CatalogEntry.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://hl7.erp.uno/schema/CatalogEntry.schema.json",
  "$ref": "#/definitions/CatalogEntry",
  "description": "see https://hl7.org/fhir/R4/json.html for information about the FHIR Json Schemas",
  "definitions": {
    "uri": {
      "pattern": "^\\S*$",
      "type": "string",
      "description": "String of characters used to identify a name or a resource"
    },
    "code": {
      "pattern": "^[^\\s]+( [^\\s]+)*$",
      "type": "string",
      "description": "A string which has at least one character and no leading or trailing whitespace and where there is no whitespace other than single spaces in the contents"
    },
    "dateTime": {
      "pattern": "^([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)(-(0[1-9]|1[0-2])(-(0[1-9]|[1-2][0-9]|3[0-1])(T([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\\.[0-9]{1,9})?)?)?(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00)?)?)?$",
      "type": "string",
      "description": "A date, date-time or partial date (e.g. just year or year + month).  If hours and minutes are specified, a UTC offset SHALL be populated. The format is a union of the schema types gYear, gYearMonth, date and dateTime. Seconds must be provided due to schema type constraints but may be zero-filled and may be ignored.                 Dates SHALL be valid dates."
    },
    "CatalogEntry": {
      "description": "Catalog entries are wrappers that contextualize items included in a catalog.",
      "properties": {
        "resourceType": {
          "description": "This is a CatalogEntry resource",
          "const": "CatalogEntry"
        },
        "id": {
          "description": "The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.",
          "type": "string"
        },
        "meta": {
          "description": "The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.",
          "$ref": "Meta.schema.json#/definitions/Meta"
        },
        "implicitRules": {
          "description": "A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc.",
          "$ref": "#/definitions/uri"
        },
        "_implicitRules": {
          "description": "Extensions for implicitRules",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "language": {
          "description": "The base language in which the resource is written.",
          "$ref": "#/definitions/code"
        },
        "_language": {
          "description": "Extensions for language",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "text": {
          "description": "A human-readable narrative that contains a summary of the resource and can be used to represent the content of the resource to a human. The narrative need not encode all the structured data, but is required to contain sufficient detail to make it \"clinically safe\" for a human to just read the narrative. Resource definitions may define what content should be represented in the narrative to ensure clinical safety.",
          "$ref": "Narrative.schema.json#/definitions/Narrative"
        },
        "contained": {
          "description": "These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction scope.",
          "items": {
            "$ref": "ResourceList.schema.json#/definitions/ResourceList"
          },
          "type": "array"
        },
        "extension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "modifierExtension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding of the containing element\u0027s descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer is allowed to define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.\n\nModifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "identifier": {
          "description": "Used in supporting different identifiers for the same product, e.g. manufacturer code and retailer code.",
          "items": {
            "$ref": "Identifier.schema.json#/definitions/Identifier"
          },
          "type": "array"
        },
        "type": {
          "description": "The type of item - medication, device, service, protocol or other.",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "orderable": {
          "description": "Whether the entry represents an orderable item.",
          "type": "boolean"
        },
        "_orderable": {
          "description": "Extensions for orderable",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "referencedItem": {
          "description": "The item in a catalog or definition.",
          "$ref": "Reference.schema.json#/definitions/Reference"
        },
        "additionalIdentifier": {
          "description": "Used in supporting related concepts, e.g. NDC to RxNorm.",
          "items": {
            "$ref": "Identifier.schema.json#/definitions/Identifier"
          },
          "type": "array"
        },
        "classification": {
          "description": "Classes of devices, or ATC for medication.",
          "items": {
            "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
          },
          "type": "array"
        },
        "status": {
          "description": "Used to support catalog exchange even for unsupported products, e.g. getting list of medications even if not prescribable.",
          "enum": [
            "draft",
            "active",
            "retired",
            "unknown"
          ]
        },
        "_status": {
          "description": "Extensions for status",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "validityPeriod": {
          "description": "The time period in which this catalog entry is expected to be active.",
          "$ref": "Period.schema.json#/definitions/Period"
        },
        "validTo": {
          "description": "The date until which this catalog entry is expected to be active.",
          "$ref": "#/definitions/dateTime"
        },
        "_validTo": {
          "description": "Extensions for validTo",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "lastUpdated": {
          "description": "Typically date of issue is different from the beginning of the validity. This can be used to see when an item was last updated.",
          "$ref": "#/definitions/dateTime"
        },
        "_lastUpdated": {
          "description": "Extensions for lastUpdated",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "additionalCharacteristic": {
          "description": "Used for examplefor Out of Formulary, or any specifics.",
          "items": {
            "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
          },
          "type": "array"
        },
        "additionalClassification": {
          "description": "User for example for ATC classification, or.",
          "items": {
            "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
          },
          "type": "array"
        },
        "relatedEntry": {
          "description": "Used for example, to point to a substance, or to a device used to administer a medication.",
          "items": {
            "$ref": "#/definitions/CatalogEntry_RelatedEntry"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "required": [
        "resourceType",
        "referencedItem"
      ]
    },
    "CatalogEntry_RelatedEntry": {
      "description": "Catalog entries are wrappers that contextualize items included in a catalog.",
      "properties": {
        "id": {
          "description": "Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.",
          "type": "string"
        },
        "extension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "modifierExtension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element\u0027s descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.\n\nModifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "relationtype": {
          "description": "The type of relation to the related item: child, parent, packageContent, containerPackage, usedIn, uses, requires, etc.",
          "enum": [
            "triggers",
            "is-replaced-by"
          ]
        },
        "_relationtype": {
          "description": "Extensions for relationtype",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "item": {
          "description": "The reference to the related item.",
          "$ref": "Reference.schema.json#/definitions/Reference"
        }
      },
      "additionalProperties": false,
      "required": [
        "item"
      ]
    }
  }
}

=== erpuno/hl7/priv/samples/CatalogEntry/CatalogEntry.json
{
  "resourceType": "CatalogEntry",
  "id": "example",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">[Put rendering here]</div>"
  },
  "identifier": [
    {
      "system": "http://example.com/identifier",
      "value": "123"
    }
  ],
  "type": {
    "text": "Medication"
  },
  "orderable": true,
  "referencedItem": {
    "reference": "Medication/123"
  }
}
