=== erpuno/hl7/schema/DeviceUsage.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://hl7.erp.uno/schema/DeviceUsage.schema.json",
  "$ref": "#/definitions/DeviceUsage",
  "description": "see https://hl7.org/fhir/R5/json.html for information about the FHIR Json Schemas",
  "definitions": {
    "dateTime": {
      "pattern": "^([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)(-(0[1-9]|1[0-2])(-(0[1-9]|[1-2][0-9]|3[0-1])(T([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\\.[0-9]{1,9})?)?)?(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00)?)?)?$",
      "type": "string",
      "description": "A date, date-time or partial date (e.g. just year or year + month).  If hours and minutes are specified, a UTC offset SHALL be populated. The format is a union of the schema types gYear, gYearMonth, date and dateTime. Seconds must be provided due to schema type constraints but may be zero-filled and may be ignored.                 Dates SHALL be valid dates."
    },
    "code": {
      "pattern": "^[^\\s]+( [^\\s]+)*$",
      "type": "string",
      "description": "A string which has at least one character and no leading or trailing whitespace and where there is no whitespace other than single spaces in the contents"
    },
    "uri": {
      "pattern": "^\\S*$",
      "type": "string",
      "description": "String of characters used to identify a name or a resource"
    },
    "DeviceUsage": {
      "description": "A record of a device being used by a patient where the record is the result of a report from the patient or a clinician.",
      "properties": {
        "resourceType": {
          "description": "This is a DeviceUsage resource",
          "const": "DeviceUsage"
        },
        "id": {
          "description": "The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.",
          "type": "string"
        },
        "meta": {
          "description": "The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.",
          "$ref": "Meta.schema.json#/definitions/Meta"
        },
        "implicitRules": {
          "description": "A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc.",
          "$ref": "#/definitions/uri"
        },
        "_implicitRules": {
          "description": "Extensions for implicitRules",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "language": {
          "description": "The base language in which the resource is written.",
          "$ref": "#/definitions/code"
        },
        "_language": {
          "description": "Extensions for language",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "text": {
          "description": "A human-readable narrative that contains a summary of the resource and can be used to represent the content of the resource to a human. The narrative need not encode all the structured data, but is required to contain sufficient detail to make it \"clinically safe\" for a human to just read the narrative. Resource definitions may define what content should be represented in the narrative to ensure clinical safety.",
          "$ref": "Narrative.schema.json#/definitions/Narrative"
        },
        "contained": {
          "description": "These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, nor can they have their own independent transaction scope. This is allowed to be a Parameters resource if and only if it is referenced by a resource that provides context/meaning.",
          "items": {
            "$ref": "ResourceList.schema.json#/definitions/ResourceList"
          },
          "type": "array"
        },
        "extension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "modifierExtension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding of the containing element\u0027s descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer is allowed to define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.\n\nModifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "identifier": {
          "description": "An external identifier for this statement such as an IRI.",
          "items": {
            "$ref": "Identifier.schema.json#/definitions/Identifier"
          },
          "type": "array"
        },
        "basedOn": {
          "description": "A plan, proposal or order that is fulfilled in whole or in part by this DeviceUsage.",
          "items": {
            "$ref": "Reference.schema.json#/definitions/Reference"
          },
          "type": "array"
        },
        "status": {
          "description": "A code representing the patient or other source\u0027s judgment about the state of the device used that this statement is about.  Generally this will be active or completed.",
          "$ref": "#/definitions/code"
        },
        "_status": {
          "description": "Extensions for status",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "category": {
          "description": "This attribute indicates a category for the statement - The device statement may be made in an inpatient or outpatient settting (inpatient | outpatient | community | patientspecified).",
          "items": {
            "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
          },
          "type": "array"
        },
        "patient": {
          "description": "The patient who used the device.",
          "$ref": "Reference.schema.json#/definitions/Reference"
        },
        "derivedFrom": {
          "description": "Allows linking the DeviceUsage to the underlying Request, or to other information that supports or is used to derive the DeviceUsage.",
          "items": {
            "$ref": "Reference.schema.json#/definitions/Reference"
          },
          "type": "array"
        },
        "context": {
          "description": "The encounter or episode of care that establishes the context for this device use statement.",
          "$ref": "Reference.schema.json#/definitions/Reference"
        },
        "timingTiming": {
          "description": "How often the device was used.",
          "$ref": "Timing.schema.json#/definitions/Timing"
        },
        "timingPeriod": {
          "description": "How often the device was used.",
          "$ref": "Period.schema.json#/definitions/Period"
        },
        "timingDateTime": {
          "description": "How often the device was used.",
          "pattern": "^([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)(-(0[1-9]|1[0-2])(-(0[1-9]|[1-2][0-9]|3[0-1])(T([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\\.[0-9]{1,9})?)?)?(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00)?)?)?$",
          "type": "string"
        },
        "_timingDateTime": {
          "description": "Extensions for timingDateTime",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "dateAsserted": {
          "description": "The time at which the statement was recorded by informationSource.",
          "$ref": "#/definitions/dateTime"
        },
        "_dateAsserted": {
          "description": "Extensions for dateAsserted",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "usageStatus": {
          "description": "The status of the device usage, for example always, sometimes, never. This is not the same as the status of the statement.",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "usageReason": {
          "description": "The reason for asserting the usage status - for example forgot, lost, stolen, broken.",
          "items": {
            "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
          },
          "type": "array"
        },
        "adherence": {
          "description": "This indicates how or if the device is being used.",
          "$ref": "#/definitions/DeviceUsage_Adherence"
        },
        "informationSource": {
          "description": "Who reported the device was being used by the patient.",
          "$ref": "Reference.schema.json#/definitions/Reference"
        },
        "device": {
          "description": "Code or Reference to device used.",
          "$ref": "CodeableReference.schema.json#/definitions/CodeableReference"
        },
        "reason": {
          "description": "Reason or justification for the use of the device. A coded concept, or another resource whose existence justifies this DeviceUsage.",
          "items": {
            "$ref": "CodeableReference.schema.json#/definitions/CodeableReference"
          },
          "type": "array"
        },
        "bodySite": {
          "description": "Indicates the anotomic location on the subject\u0027s body where the device was used ( i.e. the target).",
          "$ref": "CodeableReference.schema.json#/definitions/CodeableReference"
        },
        "note": {
          "description": "Details about the device statement that were not represented at all or sufficiently in one of the attributes provided in a class. These may include for example a comment, an instruction, or a note associated with the statement.",
          "items": {
            "$ref": "Annotation.schema.json#/definitions/Annotation"
          },
          "type": "array"
        }
      },
      "type": "object",
      "additionalProperties": false,
      "required": [
        "patient",
        "device",
        "resourceType"
      ]
    },
    "DeviceUsage_Adherence": {
      "description": "A record of a device being used by a patient where the record is the result of a report from the patient or a clinician.",
      "properties": {
        "id": {
          "description": "Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.",
          "type": "string"
        },
        "extension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "modifierExtension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element\u0027s descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.\n\nModifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "code": {
          "description": "Type of adherence.",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "reason": {
          "description": "Reason for adherence type.",
          "items": {
            "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
          },
          "type": "array"
        }
      },
      "type": "object",
      "additionalProperties": false,
      "required": [
        "reason",
        "code"
      ]
    }
  }
}

=== erpuno/hl7/samples/json/DeviceUsage/DeviceUsage.json
{
  "resourceType": "DeviceUsage",
  "id": "example",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Generated Narrative: DeviceUsage</b><a name=\"example\"> </a></p><div style=\"display: inline-block; background-color: #d9e0e7; padding: 6px; margin: 4px; border: 1px solid #8da1b4; border-radius: 5px; line-height: 60%\"><p style=\"margin-bottom: 0px\">Resource DeviceUsage &quot;example&quot; </p></div><p><b>identifier</b>: id:Â 51ebb7a9-4e3a-4360-9a05-0cc2d869086f</p><p><b>status</b>: active</p><p><b>patient</b>: <a href=\"patient-example.html\">Patient/example</a> &quot;Peter CHALMERS&quot;</p><h3>Devices</h3><table class=\"grid\"><tr><td>-</td><td><b>Concept</b></td></tr><tr><td>*</td><td>ACME defribillator <span style=\"background: LightGoldenRodYellow; margin: 4px; border: 1px solid khaki\"> ()</span></td></tr></table><h3>Reasons</h3><table class=\"grid\"><tr><td>-</td><td><b>Reference</b></td></tr><tr><td>*</td><td><a href=\"condition-example.html\">Condition/example: PHx of Appendectomy (surgery)</a></td></tr></table></div>"
  },
  "identifier": [
    {
      "system": "http:goodhealth.org/identifiers",
      "value": "51ebb7a9-4e3a-4360-9a05-0cc2d869086f"
    }
  ],
  "status": "active",
  "patient": {
    "reference": "Patient/example"
  },
  "device": {
    "concept": {
      "text": "ACME defribillator"
    }
  },
  "reason": [
    {
      "reference": {
        "reference": "Condition/example",
        "display": "PHx of Appendectomy (surgery)"
      }
    }
  ],
  "meta": {
    "tag": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/v3-ActReason",
        "code": "HTEST",
        "display": "test health data"
      }
    ]
  }
}
