=== erpuno/hl7/schema/MedicinalProductPackaged.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://hl7.erp.uno/schema/MedicinalProductPackaged.schema.json",
  "$ref": "#/definitions/MedicinalProductPackaged",
  "description": "see https://hl7.org/fhir/R4/json.html for information about the FHIR Json Schemas",
  "definitions": {
    "ProdCharacteristic":{},
    "markdown": {
      "pattern": "^^[\\s\\S]+$$",
      "type": "string",
      "description": "A string that may contain Github Flavored Markdown syntax for optional processing by a mark down presentation engine"
    },
    "canonical": {},
     "dateTime": {
      "description": "The date that the list was prepared.",
      "type": "string",
      "pattern": "-?([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)(-(0[1-9]|1[0-2])(-(0[1-9]|[1-2][0-9]|3[0-1])(T([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\\.[0-9]+)?(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00)))?)?)?"
    },
    "code": {
      "pattern": "^[^\\s]+( [^\\s]+)*$",
      "type": "string",
      "description": "A string which has at least one character and no leading or trailing whitespace and where there is no whitespace other than single spaces in the contents"
    },
    "uri": {
      "pattern": "^\\S*$",
      "type": "string",
      "description": "String of characters used to identify a name or a resource"
    },
    "MedicinalProductPackaged": {
      "description": "A medicinal product in a container or package.",
      "properties": {
        "resourceType": {
          "description": "This is a MedicinalProductPackaged resource",
          "const": "MedicinalProductPackaged"
        },
        "id": {
          "description": "The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.",
          "type": "string"
        },
        "meta": {
          "description": "The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.",
          "$ref": "Meta.schema.json#/definitions/Meta"
        },
        "implicitRules": {
          "description": "A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc.",
          "$ref": "#/definitions/uri"
        },
        "_implicitRules": {
          "description": "Extensions for implicitRules",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "language": {
          "description": "The base language in which the resource is written.",
          "$ref": "#/definitions/code"
        },
        "_language": {
          "description": "Extensions for language",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "text": {
          "description": "A human-readable narrative that contains a summary of the resource and can be used to represent the content of the resource to a human. The narrative need not encode all the structured data, but is required to contain sufficient detail to make it \"clinically safe\" for a human to just read the narrative. Resource definitions may define what content should be represented in the narrative to ensure clinical safety.",
          "$ref": "Narrative.schema.json#/definitions/Narrative"
        },
        "contained": {
          "description": "These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction scope.",
          "items": {
            "$ref": "ResourceList.schema.json#/definitions/ResourceList"
          },
          "type": "array"
        },
        "extension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "modifierExtension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding of the containing element\u0027s descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer is allowed to define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.\n\nModifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "identifier": {
          "description": "Unique identifier.",
          "items": {
            "$ref": "Identifier.schema.json#/definitions/Identifier"
          },
          "type": "array"
        },
        "subject": {
          "description": "The product with this is a pack for.",
          "items": {
            "$ref": "Reference.schema.json#/definitions/Reference"
          },
          "type": "array"
        },
        "description": {
          "description": "Textual description.",
          "type": "string"
        },
        "_description": {
          "description": "Extensions for description",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "legalStatusOfSupply": {
          "description": "The legal status of supply of the medicinal product as classified by the regulator.",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "marketingStatus": {
          "description": "Marketing information.",
          "items": {
            "$ref": "MarketingStatus.schema.json#/definitions/MarketingStatus"
          },
          "type": "array"
        },
        "marketingAuthorization": {
          "description": "Manufacturer of this Package Item.",
          "$ref": "Reference.schema.json#/definitions/Reference"
        },
        "manufacturer": {
          "description": "Manufacturer of this Package Item.",
          "items": {
            "$ref": "Reference.schema.json#/definitions/Reference"
          },
          "type": "array"
        },
        "batchIdentifier": {
          "description": "Batch numbering.",
          "items": {
            "$ref": "#/definitions/MedicinalProductPackaged_BatchIdentifier"
          },
          "type": "array"
        },
        "packageItem": {
          "description": "A packaging item, as a contained for medicine, possibly with other packaging items within.",
          "items": {
            "$ref": "#/definitions/MedicinalProductPackaged_PackageItem"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "required": [
        "packageItem",
        "resourceType"
      ]
    },
    "MedicinalProductPackaged_BatchIdentifier": {
      "description": "A medicinal product in a container or package.",
      "properties": {
        "id": {
          "description": "Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.",
          "type": "string"
        },
        "extension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "modifierExtension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element\u0027s descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.\n\nModifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "outerPackaging": {
          "description": "A number appearing on the outer packaging of a specific batch.",
          "$ref": "Identifier.schema.json#/definitions/Identifier"
        },
        "immediatePackaging": {
          "description": "A number appearing on the immediate packaging (and not the outer packaging).",
          "$ref": "Identifier.schema.json#/definitions/Identifier"
        }
      },
      "additionalProperties": false,
      "required": [
        "outerPackaging"
      ]
    },
    "MedicinalProductPackaged_PackageItem": {
      "description": "A medicinal product in a container or package.",
      "properties": {
        "id": {
          "description": "Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.",
          "type": "string"
        },
        "extension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "modifierExtension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element\u0027s descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.\n\nModifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "identifier": {
          "description": "Including possibly Data Carrier Identifier.",
          "items": {
            "$ref": "Identifier.schema.json#/definitions/Identifier"
          },
          "type": "array"
        },
        "type": {
          "description": "The physical type of the container of the medicine.",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "quantity": {
          "description": "The quantity of this package in the medicinal product, at the current level of packaging. The outermost is always 1.",
          "$ref": "Quantity.schema.json#/definitions/Quantity"
        },
        "material": {
          "description": "Material type of the package item.",
          "items": {
            "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
          },
          "type": "array"
        },
        "alternateMaterial": {
          "description": "A possible alternate material for the packaging.",
          "items": {
            "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
          },
          "type": "array"
        },
        "device": {
          "description": "A device accompanying a medicinal product.",
          "items": {
            "$ref": "Reference.schema.json#/definitions/Reference"
          },
          "type": "array"
        },
        "manufacturedItem": {
          "description": "The manufactured item as contained in the packaged medicinal product.",
          "items": {
            "$ref": "Reference.schema.json#/definitions/Reference"
          },
          "type": "array"
        },
        "packageItem": {
          "description": "Allows containers within containers.",
          "items": {
            "$ref": "#/definitions/MedicinalProductPackaged_PackageItem"
          },
          "type": "array"
        },
        "physicalCharacteristics": {
          "description": "Dimensions, color etc.",
          "$ref": "#/definitions/ProdCharacteristic"
        },
        "otherCharacteristics": {
          "description": "Other codeable characteristics.",
          "items": {
            "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
          },
          "type": "array"
        },
        "shelfLifeStorage": {
          "description": "Shelf Life and storage information.",
          "items": {
            "$ref": "ProductShelfLife.schema.json#/definitions/ProductShelfLife"
          },
          "type": "array"
        },
        "manufacturer": {
          "description": "Manufacturer of this Package Item.",
          "items": {
            "$ref": "Reference.schema.json#/definitions/Reference"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "required": [
        "quantity",
        "type"
      ]
    }
  }
}

=== erpuno/hl7/priv/samples/MedicinalProductPackaged/MedicinalProductPackaged.json
{
  "resourceType": "MedicinalProductPackaged",
  "id": "example",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Generated Narrative with Details</b></p><p><b>id</b>: example</p><p><b>identifier</b>: {PCID}</p><p><b>description</b>: ALU-PVC/PVDC BLISTERS. CARTONS OF 10 FILM-COATED TABLETS. </p><h3>BatchIdentifiers</h3><table><tr><td>-</td><td><b>OuterPackaging</b></td></tr><tr><td>*</td><td>AAF5699</td></tr></table><blockquote><p><b>packageItem</b></p><p><b>type</b>: Carton <span>(Details : {http://ema.europa.eu/example/packageitemcontainertype code 'Carton' = 'Carton)</span></p><p><b>quantity</b>: 1 1</p><p><b>material</b>: PVC <span>(Details : {http://ema.europa.eu/example/packageItemContainerMaterial code 'PVC' = 'PVC)</span>, PVDC <span>(Details : {http://ema.europa.eu/example/packageItemContainerMaterial code 'PVDC' = 'PVDC)</span>, alu <span>(Details : {http://ema.europa.eu/example/packageItemContainerMaterial code 'alu' = 'alu)</span></p><h3>PackageItems</h3><table><tr><td>-</td></tr><tr><td>*</td></tr></table><p><b>physicalCharacteristics</b>: </p><p><b>manufacturer</b>: <a>Organization/example</a></p></blockquote></div>"
  },
  "identifier": [
    {
      "system": "http://ema.europa.eu/example/pcid",
      "value": "{PCID}"
    }
  ],
  "description": "ALU-PVC/PVDC BLISTERS. CARTONS OF 10 FILM-COATED TABLETS. ",
  "batchIdentifier": [
    {
      "outerPackaging": {
        "system": "http://ema.europa.eu/example/baid1",
        "value": "AAF5699",
        "period": {
          "end": "2016-06-06"
        }
      }
    }
  ],
  "packageItem": [
    {
      "type": {
        "coding": [
          {
            "system": "http://ema.europa.eu/example/packageitemcontainertype",
            "code": "Carton"
          }
        ]
      },
      "quantity": {
        "value": 1,
        "unit": "1"
      },
      "material": [
        {
          "coding": [
            {
              "system": "http://ema.europa.eu/example/packageItemContainerMaterial",
              "code": "PVC"
            }
          ]
        },
        {
          "coding": [
            {
              "system": "http://ema.europa.eu/example/packageItemContainerMaterial",
              "code": "PVDC"
            }
          ]
        },
        {
          "coding": [
            {
              "system": "http://ema.europa.eu/example/packageItemContainerMaterial",
              "code": "alu"
            }
          ]
        }
      ],
      "packageItem": [
        {
          "type": {
            "coding": [
              {
                "system": "http://ema.europa.eu/example/packageitemcontainertype",
                "code": "Blister"
              }
            ]
          },
          "quantity": {
            "value": 1,
            "unit": "1"
          },
          "material": [
            {
              "coding": [
                {
                  "system": "http://ema.europa.eu/example/packageItemContainerMaterial",
                  "code": "Paperboard"
                }
              ]
            }
          ],
          "manufacturedItem": [
            {
              "reference": "MedicinalProductManufactured/example"
            }
          ],
          "physicalCharacteristics": {
            "height": {
              "value": 125,
              "unit": "mm"
            },
            "width": {
              "value": 45,
              "unit": "mm"
            }
          },
          "shelfLifeStorage": [
            {
              "type": {
                "coding": [
                  {
                    "system": "http://ema.europa.eu/example/shelfLifeTypePlaceHolder",
                    "code": "ShelfLifeofPackagedMedicinalProduct"
                  }
                ]
              },
              "period": {
                "value": 3,
                "unit": "a"
              },
              "specialPrecautionsForStorage": [
                {
                  "coding": [
                    {
                      "system": "http://ema.europa.eu/example/specialprecautionsforstorage",
                      "code": "Thismedicinalproductdoesnotrequireanyspecialstoragecondition."
                    }
                  ]
                }
              ]
            }
          ],
          "manufacturer": [
            {
              "reference": "Organization/example"
            }
          ]
        }
      ],
      "physicalCharacteristics": {
        "height": {
          "value": 50,
          "unit": "mm"
        },
        "width": {
          "value": 136,
          "unit": "mm"
        },
        "depth": {
          "value": 23.5,
          "unit": "mm"
        }
      },
      "manufacturer": [
        {
          "reference": "Organization/example"
        }
      ]
    }
  ]
}
