=== erpuno/hl7/samples/VerificationResult/VerificationResult.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://hl7.erp.uno/schema/VerificationResult.schema.json",
  "$ref": "#/definitions/VerificationResult",
  "description": "see https://hl7.org/fhir/R5/json.html for information about the FHIR Json Schemas",
  "definitions": {
    "VerificationResult": {
      "description": "Describes validation requirements, source(s), status and dates for one or more elements.",
      "properties": {
        "resourceType": {
          "description": "This is a VerificationResult resource",
          "const": "VerificationResult"
        },
        "id": {
          "description": "The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.",
          "type": "string"
        },
        "meta": {
          "description": "The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.",
          "$ref": "Meta.schema.json#/definitions/Meta"
        },
        "implicitRules": {
          "description": "A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc.",
          "$ref": "#/definitions/uri"
        },
        "_implicitRules": {
          "description": "Extensions for implicitRules",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "language": {
          "description": "The base language in which the resource is written.",
          "$ref": "#/definitions/code"
        },
        "_language": {
          "description": "Extensions for language",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "text": {
          "description": "A human-readable narrative that contains a summary of the resource and can be used to represent the content of the resource to a human. The narrative need not encode all the structured data, but is required to contain sufficient detail to make it \"clinically safe\" for a human to just read the narrative. Resource definitions may define what content should be represented in the narrative to ensure clinical safety.",
          "$ref": "Narrative.schema.json#/definitions/Narrative"
        },
        "contained": {
          "description": "These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, nor can they have their own independent transaction scope. This is allowed to be a Parameters resource if and only if it is referenced by a resource that provides context/meaning.",
          "items": {
            "$ref": "ResourceList.schema.json#/definitions/ResourceList"
          },
          "type": "array"
        },
        "extension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "modifierExtension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding of the containing element\u0027s descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer is allowed to define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.\n\nModifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "target": {
          "description": "A resource that was validated.",
          "items": {
            "$ref": "Reference.schema.json#/definitions/Reference"
          },
          "type": "array"
        },
        "targetLocation": {
          "description": "The fhirpath location(s) within the resource that was validated.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "_targetLocation": {
          "description": "Extensions for targetLocation",
          "items": {
            "$ref": "Element.schema.json#/definitions/Element"
          },
          "type": "array"
        },
        "need": {
          "description": "The frequency with which the target must be validated (none; initial; periodic).",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "status": {
          "description": "The validation status of the target (attested; validated; in process; requires revalidation; validation failed; revalidation failed).",
          "$ref": "#/definitions/code"
        },
        "_status": {
          "description": "Extensions for status",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "statusDate": {
          "description": "When the validation status was updated.",
          "$ref": "#/definitions/dateTime"
        },
        "_statusDate": {
          "description": "Extensions for statusDate",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "validationType": {
          "description": "What the target is validated against (nothing; primary source; multiple sources).",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "validationProcess": {
          "description": "The primary process by which the target is validated (edit check; value set; primary source; multiple sources; standalone; in context).",
          "items": {
            "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
          },
          "type": "array"
        },
        "frequency": {
          "description": "Frequency of revalidation.",
          "$ref": "Timing.schema.json#/definitions/Timing"
        },
        "lastPerformed": {
          "description": "The date/time validation was last completed (including failed validations).",
          "$ref": "#/definitions/dateTime"
        },
        "_lastPerformed": {
          "description": "Extensions for lastPerformed",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "nextScheduled": {
          "description": "The date when target is next validated, if appropriate.",
          "$ref": "#/definitions/date"
        },
        "_nextScheduled": {
          "description": "Extensions for nextScheduled",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "failureAction": {
          "description": "The result if validation fails (fatal; warning; record only; none).",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "primarySource": {
          "description": "Information about the primary source(s) involved in validation.",
          "items": {
            "$ref": "#/definitions/VerificationResult_PrimarySource"
          },
          "type": "array"
        },
        "attestation": {
          "description": "Information about the entity attesting to information.",
          "$ref": "#/definitions/VerificationResult_Attestation"
        },
        "validator": {
          "description": "Information about the entity validating information.",
          "items": {
            "$ref": "#/definitions/VerificationResult_Validator"
          },
          "type": "array"
        }
      },
      "type": "object",
      "additionalProperties": false,
      "required": [
        "resourceType"
      ]
    },
    "VerificationResult_PrimarySource": {
      "description": "Describes validation requirements, source(s), status and dates for one or more elements.",
      "properties": {
        "id": {
          "description": "Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.",
          "type": "string"
        },
        "extension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "modifierExtension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element\u0027s descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.\n\nModifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "who": {
          "description": "Reference to the primary source.",
          "$ref": "Reference.schema.json#/definitions/Reference"
        },
        "type": {
          "description": "Type of primary source (License Board; Primary Education; Continuing Education; Postal Service; Relationship owner; Registration Authority; legal source; issuing source; authoritative source).",
          "items": {
            "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
          },
          "type": "array"
        },
        "communicationMethod": {
          "description": "Method for communicating with the primary source (manual; API; Push).",
          "items": {
            "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
          },
          "type": "array"
        },
        "validationStatus": {
          "description": "Status of the validation of the target against the primary source (successful; failed; unknown).",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "validationDate": {
          "description": "When the target was validated against the primary source.",
          "$ref": "#/definitions/dateTime"
        },
        "_validationDate": {
          "description": "Extensions for validationDate",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "canPushUpdates": {
          "description": "Ability of the primary source to push updates/alerts (yes; no; undetermined).",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "pushTypeAvailable": {
          "description": "Type of alerts/updates the primary source can send (specific requested changes; any changes; as defined by source).",
          "items": {
            "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
          },
          "type": "array"
        }
      },
      "type": "object",
      "additionalProperties": false
    },
    "VerificationResult_Attestation": {
      "description": "Describes validation requirements, source(s), status and dates for one or more elements.",
      "properties": {
        "id": {
          "description": "Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.",
          "type": "string"
        },
        "extension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "modifierExtension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element\u0027s descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.\n\nModifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "who": {
          "description": "The individual or organization attesting to information.",
          "$ref": "Reference.schema.json#/definitions/Reference"
        },
        "onBehalfOf": {
          "description": "When the who is asserting on behalf of another (organization or individual).",
          "$ref": "Reference.schema.json#/definitions/Reference"
        },
        "communicationMethod": {
          "description": "The method by which attested information was submitted/retrieved (manual; API; Push).",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "date": {
          "description": "The date the information was attested to.",
          "$ref": "#/definitions/date"
        },
        "_date": {
          "description": "Extensions for date",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "sourceIdentityCertificate": {
          "description": "A digital identity certificate associated with the attestation source.",
          "type": "string"
        },
        "_sourceIdentityCertificate": {
          "description": "Extensions for sourceIdentityCertificate",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "proxyIdentityCertificate": {
          "description": "A digital identity certificate associated with the proxy entity submitting attested information on behalf of the attestation source.",
          "type": "string"
        },
        "_proxyIdentityCertificate": {
          "description": "Extensions for proxyIdentityCertificate",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "proxySignature": {
          "description": "Signed assertion by the proxy entity indicating that they have the right to submit attested information on behalf of the attestation source.",
          "$ref": "Signature.schema.json#/definitions/Signature"
        },
        "sourceSignature": {
          "description": "Signed assertion by the attestation source that they have attested to the information.",
          "$ref": "Signature.schema.json#/definitions/Signature"
        }
      },
      "type": "object",
      "additionalProperties": false
    },
    "VerificationResult_Validator": {
      "description": "Describes validation requirements, source(s), status and dates for one or more elements.",
      "properties": {
        "id": {
          "description": "Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.",
          "type": "string"
        },
        "extension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "modifierExtension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element\u0027s descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.\n\nModifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "organization": {
          "description": "Reference to the organization validating information.",
          "$ref": "Reference.schema.json#/definitions/Reference"
        },
        "identityCertificate": {
          "description": "A digital identity certificate associated with the validator.",
          "type": "string"
        },
        "_identityCertificate": {
          "description": "Extensions for identityCertificate",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "attestationSignature": {
          "description": "Signed assertion by the validator that they have validated the information.",
          "$ref": "Signature.schema.json#/definitions/Signature"
        }
      },
      "type": "object",
      "additionalProperties": false,
      "required": [
        "organization"
      ]
    }
  }
}

=== erpuno/hl7/samples/VerificationResult/VerificationResult.json
{
  "resourceType" : "VerificationResult",
  "id" : "example",
  "text" : {
    "status" : "generated",
    "div" : "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Generated Narrative: VerificationResult</b><a name=\"example\"> </a></p><div style=\"display: inline-block; background-color: #d9e0e7; padding: 6px; margin: 4px; border: 1px solid #8da1b4; border-radius: 5px; line-height: 60%\"><p style=\"margin-bottom: 0px\">Resource VerificationResult &quot;example&quot; </p></div><p><b>status</b>: <span title=\" \n\t&lt;target&gt;\n\t\t&lt;display value=&quot;Dr Feelbetter&quot; /&gt;\n\t&lt;/target&gt;\n\t&lt;need value=&quot;initial&quot; /&gt;  \">attested</span></p></div>"
  },
  "status" : "attested"
}
