=== erpuno/hl7/priv/schema/MedicinalProductContraindication.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://hl7.erp.uno/priv/schema/MedicinalProductContraindication.schema.json",
  "$ref": "#/definitions/MedicinalProductContraindication",
  "description": "see https://hl7.org/fhir/R5/json.html for information about the FHIR Json Schemas",
  "definitions": {
    "Population": {},
    "uri": {
      "pattern": "^\\S*$",
      "type": "string",
      "description": "String of characters used to identify a name or a resource"
    },
    "code": {
      "pattern": "^[^\\s]+( [^\\s]+)*$",
      "type": "string",
      "description": "A string which has at least one character and no leading or trailing whitespace and where there is no whitespace other than single spaces in the contents"
    },
    "MedicinalProductContraindication": {
      "description": "The clinical particulars - indications, contraindications etc. of a medicinal product, including for regulatory purposes.",
      "properties": {
        "resourceType": {
          "description": "This is a MedicinalProductContraindication resource",
          "const": "MedicinalProductContraindication"
        },
        "id": {
          "description": "The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.",
          "type": "string"
        },
        "meta": {
          "description": "The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.",
          "$ref": "Meta.schema.json#/definitions/Meta"
        },
        "implicitRules": {
          "description": "A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc.",
          "$ref": "#/definitions/uri"
        },
        "_implicitRules": {
          "description": "Extensions for implicitRules",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "language": {
          "description": "The base language in which the resource is written.",
          "$ref": "#/definitions/code"
        },
        "_language": {
          "description": "Extensions for language",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "text": {
          "description": "A human-readable narrative that contains a summary of the resource and can be used to represent the content of the resource to a human. The narrative need not encode all the structured data, but is required to contain sufficient detail to make it \"clinically safe\" for a human to just read the narrative. Resource definitions may define what content should be represented in the narrative to ensure clinical safety.",
          "$ref": "Narrative.schema.json#/definitions/Narrative"
        },
        "contained": {
          "description": "These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction scope.",
          "items": {
            "$ref": "ResourceList.schema.json#/definitions/ResourceList"
          },
          "type": "array"
        },
        "extension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "modifierExtension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding of the containing element\u0027s descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer is allowed to define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.\n\nModifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "subject": {
          "description": "The medication for which this is an indication.",
          "items": {
            "$ref": "Reference.schema.json#/definitions/Reference"
          },
          "type": "array"
        },
        "disease": {
          "description": "The disease, symptom or procedure for the contraindication.",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "diseaseStatus": {
          "description": "The status of the disease or symptom for the contraindication.",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "comorbidity": {
          "description": "A comorbidity (concurrent condition) or coinfection.",
          "items": {
            "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
          },
          "type": "array"
        },
        "therapeuticIndication": {
          "description": "Information about the use of the medicinal product in relation to other therapies as part of the indication.",
          "items": {
            "$ref": "Reference.schema.json#/definitions/Reference"
          },
          "type": "array"
        },
        "otherTherapy": {
          "description": "Information about the use of the medicinal product in relation to other therapies described as part of the indication.",
          "items": {
            "$ref": "#/definitions/MedicinalProductContraindication_OtherTherapy"
          },
          "type": "array"
        },
        "population": {
          "description": "The population group to which this applies.",
          "items": {
            "$ref": "#/definitions/Population"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "required": [
        "resourceType"
      ]
    },
    "MedicinalProductContraindication_OtherTherapy": {
      "description": "The clinical particulars - indications, contraindications etc. of a medicinal product, including for regulatory purposes.",
      "properties": {
        "id": {
          "description": "Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.",
          "type": "string"
        },
        "extension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "modifierExtension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element\u0027s descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.\n\nModifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "therapyRelationshipType": {
          "description": "The type of relationship between the medicinal product indication or contraindication and another therapy.",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "medicationCodeableConcept": {
          "description": "Reference to a specific medication (active substance, medicinal product or class of products) as part of an indication or contraindication.",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "medicationReference": {
          "description": "Reference to a specific medication (active substance, medicinal product or class of products) as part of an indication or contraindication.",
          "$ref": "Reference.schema.json#/definitions/Reference"
        }
      },
      "additionalProperties": false,
      "required": [
        "therapyRelationshipType"
      ]
    }
  }
}

=== erpuno/hl7/priv/samples/MedicinalProductContraindication/MedicinalProductContraindication.json
{
  "resourceType": "MedicinalProductContraindication",
  "id": "example",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Generated Narrative with Details</b></p><p><b>id</b>: example</p><p><b>disease</b>: Hepatic disease associated with coagulopathy and clinically relevant bleeding risk <span>(Details : {http://ema.europa.eu/example/contraindicationsasdisease-symptom-procedure code 'Coagulopathiesandbleedingdiatheses(exclthrombocytopenic)' = 'Coagulopathiesandbleedingdiatheses(exclthrombocytopenic))</span></p><p><b>comorbidity</b>: Hepaticdisease <span>(Details : {http://ema.europa.eu/example/comorbidity code 'Hepaticdisease' = 'Hepaticdisease)</span></p></div>"
  },
  "disease": {
    "coding": [
      {
        "system": "http://ema.europa.eu/example/contraindicationsasdisease-symptom-procedure",
        "code": "Coagulopathiesandbleedingdiatheses(exclthrombocytopenic)"
      }
    ],
    "text": "Hepatic disease associated with coagulopathy and clinically relevant bleeding risk"
  },
  "comorbidity": [
    {
      "coding": [
        {
          "system": "http://ema.europa.eu/example/comorbidity",
          "code": "Hepaticdisease"
        }
      ]
    }
  ]
}
