=== erpuno/hl7/priv/schema/MedicinalProductAuthorization.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://hl7.erp.uno/priv/schema/MedicinalProductAuthorization",
  "$ref": "#/definitions/MedicinalProductAuthorization",
  "description": "see https://hl7.org/fhir/R5/json.html for information about the FHIR Json Schemas",
  "definitions": {
    "markdown": {
      "pattern": "^^[\\s\\S]+$$",
      "type": "string",
      "description": "A string that may contain Github Flavored Markdown syntax for optional processing by a mark down presentation engine"
    },
    "dateTime": {
      "description": "The date that the list was prepared.",
      "type": "string",
      "pattern": "-?([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)(-(0[1-9]|1[0-2])(-(0[1-9]|[1-2][0-9]|3[0-1])(T([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\\.[0-9]+)?(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00)))?)?)?"
    },
    "code": {
      "pattern": "^[^\\s]+( [^\\s]+)*$",
      "type": "string",
      "description": "A string which has at least one character and no leading or trailing whitespace and where there is no whitespace other than single spaces in the contents"
    },
    "uri": {
      "pattern": "^\\S*$",
      "type": "string",
      "description": "String of characters used to identify a name or a resource"
    },
    "MedicinalProductAuthorization": {
      "description": "The regulatory authorization of a medicinal product.",
      "properties": {
        "resourceType": {
          "description": "This is a MedicinalProductAuthorization resource",
          "const": "MedicinalProductAuthorization"
        },
        "id": {
          "description": "The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.",
          "type": "string"
        },
        "meta": {
          "description": "The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.",
          "$ref": "Meta.schema.json#/definitions/Meta"
        },
        "implicitRules": {
          "description": "A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc.",
          "$ref": "#/definitions/uri"
        },
        "_implicitRules": {
          "description": "Extensions for implicitRules",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "language": {
          "description": "The base language in which the resource is written.",
          "$ref": "#/definitions/code"
        },
        "_language": {
          "description": "Extensions for language",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "text": {
          "description": "A human-readable narrative that contains a summary of the resource and can be used to represent the content of the resource to a human. The narrative need not encode all the structured data, but is required to contain sufficient detail to make it \"clinically safe\" for a human to just read the narrative. Resource definitions may define what content should be represented in the narrative to ensure clinical safety.",
          "$ref": "Narrative.schema.json#/definitions/Narrative"
        },
        "contained": {
          "description": "These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction scope.",
          "items": {
            "$ref": "ResourceList.schema.json#/definitions/ResourceList"
          },
          "type": "array"
        },
        "extension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "modifierExtension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding of the containing element\u0027s descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer is allowed to define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.\n\nModifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "identifier": {
          "description": "Business identifier for the marketing authorization, as assigned by a regulator.",
          "items": {
            "$ref": "Identifier.schema.json#/definitions/Identifier"
          },
          "type": "array"
        },
        "subject": {
          "description": "The medicinal product that is being authorized.",
          "$ref": "Reference.schema.json#/definitions/Reference"
        },
        "country": {
          "description": "The country in which the marketing authorization has been granted.",
          "items": {
            "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
          },
          "type": "array"
        },
        "jurisdiction": {
          "description": "Jurisdiction within a country.",
          "items": {
            "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
          },
          "type": "array"
        },
        "status": {
          "description": "The status of the marketing authorization.",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "statusDate": {
          "description": "The date at which the given status has become applicable.",
          "$ref": "#/definitions/dateTime"
        },
        "_statusDate": {
          "description": "Extensions for statusDate",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "restoreDate": {
          "description": "The date when a suspended the marketing or the marketing authorization of the product is anticipated to be restored.",
          "$ref": "#/definitions/dateTime"
        },
        "_restoreDate": {
          "description": "Extensions for restoreDate",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "validityPeriod": {
          "description": "The beginning of the time period in which the marketing authorization is in the specific status shall be specified A complete date consisting of day, month and year shall be specified using the ISO 8601 date format.",
          "$ref": "Period.schema.json#/definitions/Period"
        },
        "dataExclusivityPeriod": {
          "description": "A period of time after authorization before generic product applicatiosn can be submitted.",
          "$ref": "Period.schema.json#/definitions/Period"
        },
        "dateOfFirstAuthorization": {
          "description": "The date when the first authorization was granted by a Medicines Regulatory Agency.",
          "$ref": "#/definitions/dateTime"
        },
        "_dateOfFirstAuthorization": {
          "description": "Extensions for dateOfFirstAuthorization",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "internationalBirthDate": {
          "description": "Date of first marketing authorization for a company\u0027s new medicinal product in any country in the World.",
          "$ref": "#/definitions/dateTime"
        },
        "_internationalBirthDate": {
          "description": "Extensions for internationalBirthDate",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "legalBasis": {
          "description": "The legal framework against which this authorization is granted.",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "jurisdictionalAuthorization": {
          "description": "Authorization in areas within a country.",
          "items": {
            "$ref": "#/definitions/MedicinalProductAuthorization_JurisdictionalAuthorization"
          },
          "type": "array"
        },
        "holder": {
          "description": "Marketing Authorization Holder.",
          "$ref": "Reference.schema.json#/definitions/Reference"
        },
        "regulator": {
          "description": "Medicines Regulatory Agency.",
          "$ref": "Reference.schema.json#/definitions/Reference"
        },
        "procedure": {
          "description": "The regulatory procedure for granting or amending a marketing authorization.",
          "$ref": "#/definitions/MedicinalProductAuthorization_Procedure"
        }
      },
      "additionalProperties": false,
      "required": [
        "resourceType"
      ]
    },
    "MedicinalProductAuthorization_JurisdictionalAuthorization": {
      "description": "The regulatory authorization of a medicinal product.",
      "properties": {
        "id": {
          "description": "Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.",
          "type": "string"
        },
        "extension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "modifierExtension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element\u0027s descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.\n\nModifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "identifier": {
          "description": "The assigned number for the marketing authorization.",
          "items": {
            "$ref": "Identifier.schema.json#/definitions/Identifier"
          },
          "type": "array"
        },
        "country": {
          "description": "Country of authorization.",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "jurisdiction": {
          "description": "Jurisdiction within a country.",
          "items": {
            "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
          },
          "type": "array"
        },
        "legalStatusOfSupply": {
          "description": "The legal status of supply in a jurisdiction or region.",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "validityPeriod": {
          "description": "The start and expected end date of the authorization.",
          "$ref": "Period.schema.json#/definitions/Period"
        }
      },
      "additionalProperties": false
    },
    "MedicinalProductAuthorization_Procedure": {
      "description": "The regulatory authorization of a medicinal product.",
      "properties": {
        "id": {
          "description": "Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.",
          "type": "string"
        },
        "extension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "modifierExtension": {
          "description": "May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element\u0027s descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.\n\nModifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).",
          "items": {
            "$ref": "Extension.schema.json#/definitions/Extension"
          },
          "type": "array"
        },
        "identifier": {
          "description": "Identifier for this procedure.",
          "$ref": "Identifier.schema.json#/definitions/Identifier"
        },
        "type": {
          "description": "Type of procedure.",
          "$ref": "CodeableConcept.schema.json#/definitions/CodeableConcept"
        },
        "datePeriod": {
          "description": "Date of procedure.",
          "$ref": "Period.schema.json#/definitions/Period"
        },
        "dateDateTime": {
          "description": "Date of procedure.",
          "pattern": "^([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)(-(0[1-9]|1[0-2])(-(0[1-9]|[1-2][0-9]|3[0-1])(T([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\\.[0-9]+)?(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00)))?)?)?$",
          "type": "string"
        },
        "_dateDateTime": {
          "description": "Extensions for dateDateTime",
          "$ref": "Element.schema.json#/definitions/Element"
        },
        "application": {
          "description": "Applcations submitted to obtain a marketing authorization.",
          "items": {
            "$ref": "#/definitions/MedicinalProductAuthorization_Procedure"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "required": [
        "type"
      ]
    }
  }
}

=== erpuno/hl7/priv/samples/MedicinalProductAuthorization/MedicinalProductAuthorization.json
{
  "resourceType": "MedicinalProductAuthorization",
  "id": "example",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Generated Narrative with Details</b></p><p><b>id</b>: example</p><p><b>identifier</b>: EU/1/11/999/001</p><p><b>country</b>: EU <span>(Details : {http://ema.europa.eu/example/country code 'EU' = 'EU)</span></p><p><b>status</b>: active <span>(Details : {http://ema.europa.eu/example/authorisationstatus code 'active' = 'active)</span></p><p><b>statusDate</b>: Jan 14, 2015</p><p><b>validityPeriod</b>: Aug 16, 2015 --&gt; May 20, 2020</p><p><b>dataExclusivityPeriod</b>: Aug 15, 2010 --&gt; Aug 15, 2020</p><p><b>dateOfFirstAuthorization</b>: Aug 15, 2010</p><p><b>internationalBirthDate</b>: Aug 15, 2010</p><blockquote><p><b>jurisdictionalAuthorization</b></p><p><b>identifier</b>: 123-456-789</p><p><b>country</b>: NO <span>(Details : {http://ema.europa.eu/example/countryCode code 'NO' = 'NO)</span></p></blockquote><blockquote><p><b>jurisdictionalAuthorization</b></p><p><b>identifier</b>: 123-456-123</p><p><b>country</b>: NO <span>(Details : {http://ema.europa.eu/example/countryCode code 'NO' = 'NO)</span></p></blockquote><p><b>holder</b>: <a>Organization/example</a></p><p><b>regulator</b>: <a>Organization/example</a></p><blockquote><p><b>procedure</b></p><p><b>identifier</b>: EMEA/H/C/009999/IA/0099/G</p><p><b>type</b>: VariationTypeIA <span>(Details : {http://ema.europa.eu/example/marketingAuthorisationProcedureType code 'VariationTypeIA' = 'VariationTypeIA)</span></p><p><b>date</b>: Aug 2, 2015 --&gt; Aug 21, 2015</p><h3>Applications</h3><table><tr><td>-</td></tr><tr><td>*</td></tr></table></blockquote></div>"
  },
  "identifier": [
    {
      "system": "http://ema.europa.eu/example/marketingAuthorisationNumber",
      "value": "EU/1/11/999/001"
    }
  ],
  "country": [
    {
      "coding": [
        {
          "system": "http://ema.europa.eu/example/country",
          "code": "EU"
        }
      ]
    }
  ],
  "status": {
    "coding": [
      {
        "system": "http://ema.europa.eu/example/authorisationstatus",
        "code": "active"
      }
    ]
  },
  "statusDate": "2015-01-14",
  "validityPeriod": {
    "start": "2015-08-16",
    "end": "2020-05-20"
  },
  "dataExclusivityPeriod": {
    "start": "2010-08-15",
    "end": "2020-08-15"
  },
  "dateOfFirstAuthorization": "2010-08-15",
  "internationalBirthDate": "2010-08-15",
  "jurisdictionalAuthorization": [
    {
      "id": "1",
      "identifier": [
        {
          "system": "http://ema.europa.eu/example/marketingauthorisationnumber",
          "value": "123-456-789"
        }
      ],
      "country": {
        "coding": [
          {
            "system": "http://ema.europa.eu/example/countryCode",
            "code": "NO"
          }
        ]
      }
    },
    {
      "id": "2",
      "identifier": [
        {
          "system": "http://ema.europa.eu/example/marketingauthorisationnumber",
          "value": "123-456-123"
        }
      ],
      "country": {
        "coding": [
          {
            "system": "http://ema.europa.eu/example/countryCode",
            "code": "NO"
          }
        ]
      }
    }
  ],
  "holder": {
    "reference": "Organization/example"
  },
  "regulator": {
    "reference": "Organization/example"
  },
  "procedure": {
    "identifier": {
      "system": "http://ema.europa.eu/example/procedureidentifier-number",
      "value": "EMEA/H/C/009999/IA/0099/G"
    },
    "type": {
      "coding": [
        {
          "system": "http://ema.europa.eu/example/marketingAuthorisationProcedureType",
          "code": "VariationTypeIA"
        }
      ]
    },
    "datePeriod": {
      "start": "2015-08-02",
      "end": "2015-08-21"
    },
    "application": [
      {
        "identifier": {
          "system": "http://ema.europa.eu/example/applicationidentifier-number",
          "value": "IA38G"
        },
        "type": {
          "coding": [
            {
              "system": "http://ema.europa.eu/example/marketingAuthorisationApplicationType",
              "code": "GroupTypeIAVariationNotification"
            }
          ]
        },
        "dateDateTime": "2015-08-01"
      }
    ]
  }
}
